### PR TITLE
Setup shell fix

### PR DESCRIPTION
**Pull request by hanlray**

### CODE REVIEW

**Comment by tzach** [comment]
@hanlray the make problem was solved, Thanks!

* I get an index.html, but with no style (css)
at the console I get the following error for all CSS and JS files
```
file:///home/tzach/projects/hanlray-scylla-docs/_build/dirhtml/www.scylladb.com/css/site.css Failed to load resource: net::ERR_FILE_NOT_FOUND
```

* please only migrate content under scylladb.com/doc to the new site

**Comment by tzach** [comment]
I have second thoughts about linking from scylla-doc to scylladb.com CSS files.
I now thinks its better for scylla-doc to be self contained
@haimagami @sagish thoughts?

**Comment by hanlray** [comment]
@tzach Regarding index.html with not styles, did you view the site via livereload?

**Comment by tzach** [comment]
what is livereload?
I opened the index.html file in my browser
```
file:///home/tzach/projects/hanlray-scylla-docs/_build/dirhtml/index.html
```

**Comment by hanlray** [comment]
@tzach You're supposed to open http://127.0.0.1:5500 to view the site locally. This is the http server created by livereload by the _utils/preview.

**Comment by tzach** [comment]
> @tzach You're supposed to open http://127.0.0.1:5500 to view the site locally. This is the http server created by livereload by the _utils/preview. Just type: "make preview" will do everything for you.

Thanks. I missed that!
I still do not get proper style
image

**Comment by hanlray** [comment]
@tzach I couldn't reproduce this issue. Could I have a look at the contents of index.html you generated? Thanks.

**Comment by tzach** [comment]
Attached. Updated the suffix from html to txt so I can attach it to the issue
[view-source_127.0.0.1_5500.txt](https://github.com/scylladb/scylla-docs/files/615803/view-source_127.0.0.1_5500.txt)

**Comment by hanlray** [comment]
@tzach This is odd. In the _templates/layout.html, I have this code:
<link rel="stylesheet" type="text/css" href="//www.scylladb.com/js/vendor/slick/slick.css"/>
But the code becomes this in your generated code:
<link rel="stylesheet" type="text/css" href="www.scylladb.com/js/vendor/slick/slick.css"/>
Could you check the source code in _build/dir/html/index.html to make sure the "//" is missing in css url?

**Comment by tzach** [comment]
In `_build/dirhtml/index.html` I see

```
    <link rel="stylesheet" type="text/css" href="www.scylladb.com/js/vendor/slick/slick.css"/>
```

**Comment by hanlray** [comment]
@tzach try "make clean", it this issue still exists, try
`. bin/activate`
`pip show sphinx`
and tell me what's the sphinx version you have.
Thanks.

**Comment by tzach** [comment]
`make clean` did not helped

```
$ pip show sphinx
Name: Sphinx
Version: 1.4.9
Summary: Python documentation generator
Home-page: http://sphinx-doc.org/
Author: Georg Brandl
Author-email: georg@python.org
License: BSD
Location: /home/tzach/projects/hanlray-scylla-docs/lib/python2.7/site-packages
Requires: snowballstemmer, alabaster, Pygments, babel, docutils, Jinja2, imagesize, six

```

**Comment by hanlray** [comment]
@tzach check please

**Comment by tzach** [comment]
Thanks @hanlray I can finally see the site locally!

Few comments:
- the doc site does not have to copy the entire scylla site features. 
  * No need for top menu (Tech, Service etc)
  * Use only minimal CSS files from scylladb.com, even if the result is not 100% the same
  * Take a look at [DataStax docs](http://docs.datastax.com/en/landing_page/doc/landing_page/current.html) as an example

**Comment by hanlray** [comment]
@tzach removed the top menu and minimal CSS files now. I took a look at the DataStax docs site, but I do not understand what do you want from it.

**Comment by tzach** [comment]
@hanlray please drop the footer as all, but the social buttons and a statement:
© 2016 ScyllaDB. All rights reserved. | Last updated: 17 November 2016
The date should be automatically update with every change

**Comment by hanlray** [comment]
@tzach check please

**Comment by tzach** [comment]
@hanlray I'm merging since this PR is already huge. 
I will open issue for you to fix with additional comments.
Please send different PR per issue.
Thanks

**Pull request merged**
