### PR TITLE
add google search

### PR DESCRIPTION
**Pull request by hanlray**

### CODE REVIEW

**Comment by tzach** [comment]
Search works, but the entire header of the screen does not look good
image

@haimagami please advise

**Comment by tzach** [comment]
@hanlray, please improve the header by extending its hight so it won't cut the logo
Can you place the search below the header?

**Comment by hanlray** [comment]
@tzach I saw that https://github.com/scylladb/scylla-docs/issues/68 already include this item and you assigned to haimagami.

**Comment by tzach** [comment]
@hanlray yes, @haimagami should take care of that

**Comment by tzach** [comment]
fix by #74

**Pull request closed without merging**
